namespace USTCRVSoC_tool
{
    partial class MainForm
    {
        /// <summary>
        /// Обязательные переменные конструктора。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up all resources in use
        /// </summary>
        /// <param name="disposing">If the Managed Resource should be released as real; otherwise false</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Code generated by the form designer

        /// <summary>
        /// The designer supports the required methods - do not
        /// Use the code editor to modify the contents of this method.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.fileSelectionText = new System.Windows.Forms.TextBox();
            this.fileSelectionBtn = new System.Windows.Forms.Button();
            this.compileGroup = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.otherSaveBtn = new System.Windows.Forms.Button();
            this.saveBtn = new System.Windows.Forms.Button();
            this.codeText = new System.Windows.Forms.TextBox();
            this.compilePromptText = new System.Windows.Forms.TextBox();
            this.HexStreamGroup = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.binText = new System.Windows.Forms.TextBox();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.saveVerilog = new System.Windows.Forms.Button();
            this.compileBtn = new System.Windows.Forms.Button();
            this.tableLayoutPanel6 = new System.Windows.Forms.TableLayoutPanel();
            this.programBtn = new System.Windows.Forms.Button();
            this.portSelectionBox = new System.Windows.Forms.ComboBox();
            this.bootAddrGroup = new System.Windows.Forms.GroupBox();
            this.bootAddrTextBox = new System.Windows.Forms.TextBox();
            this.MainLayout = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel7 = new System.Windows.Forms.TableLayoutPanel();
            this.userPortTextBox = new System.Windows.Forms.TextBox();
            this.tableLayoutPanel8 = new System.Windows.Forms.TableLayoutPanel();
            this.userPortClearBtn = new System.Windows.Forms.Button();
            this.userPortOpenCloseBtn = new System.Windows.Forms.Button();
            this.userPortShowHex = new System.Windows.Forms.CheckBox();
            this.UserPortRecvCountLabel = new System.Windows.Forms.Label();
            this.MemoryDumpGroup = new System.Windows.Forms.GroupBox();
            this.MemoryDumpLayout = new System.Windows.Forms.TableLayoutPanel();
            this.MemContents = new System.Windows.Forms.TextBox();
            this.AdrLenSpecLayout = new System.Windows.Forms.TableLayoutPanel();
            this.StartAddr = new System.Windows.Forms.TextBox();
            this.Length = new System.Windows.Forms.TextBox();
            this.LengthTitle = new System.Windows.Forms.Label();
            this.StartAddrTitle = new System.Windows.Forms.Label();
            this.DUMPMemory = new System.Windows.Forms.Button();
            this.serialPort = new System.IO.Ports.SerialPort(this.components);
            this.compileGroup.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.HexStreamGroup.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            this.tableLayoutPanel5.SuspendLayout();
            this.tableLayoutPanel6.SuspendLayout();
            this.bootAddrGroup.SuspendLayout();
            this.MainLayout.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tableLayoutPanel7.SuspendLayout();
            this.tableLayoutPanel8.SuspendLayout();
            this.MemoryDumpGroup.SuspendLayout();
            this.MemoryDumpLayout.SuspendLayout();
            this.AdrLenSpecLayout.SuspendLayout();
            this.SuspendLayout();
            // 
            // fileSelectionText
            // 
            this.fileSelectionText.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.fileSelectionText.Font = new System.Drawing.Font("SimSun", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.fileSelectionText.Location = new System.Drawing.Point(4, 4);
            this.fileSelectionText.Margin = new System.Windows.Forms.Padding(4);
            this.fileSelectionText.Name = "fileSelectionText";
            this.fileSelectionText.ReadOnly = true;
            this.fileSelectionText.Size = new System.Drawing.Size(140, 24);
            this.fileSelectionText.TabIndex = 0;
            // 
            // fileSelectionBtn
            // 
            this.fileSelectionBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.fileSelectionBtn.Font = new System.Drawing.Font("SimSun", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.fileSelectionBtn.Location = new System.Drawing.Point(150, 3);
            this.fileSelectionBtn.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.fileSelectionBtn.Name = "fileSelectionBtn";
            this.fileSelectionBtn.Size = new System.Drawing.Size(86, 30);
            this.fileSelectionBtn.TabIndex = 1;
            this.fileSelectionBtn.Text = "Open...";
            this.fileSelectionBtn.UseVisualStyleBackColor = true;
            this.fileSelectionBtn.Click += new System.EventHandler(this.fileSelectionBtn_Click);
            // 
            // compileGroup
            // 
            this.compileGroup.Controls.Add(this.tableLayoutPanel3);
            this.compileGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.compileGroup.Font = new System.Drawing.Font("SimSun", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.compileGroup.Location = new System.Drawing.Point(5, 6);
            this.compileGroup.Margin = new System.Windows.Forms.Padding(5, 6, 5, 6);
            this.compileGroup.Name = "compileGroup";
            this.compileGroup.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.compileGroup.Size = new System.Drawing.Size(422, 56);
            this.compileGroup.TabIndex = 2;
            this.compileGroup.TabStop = false;
            this.compileGroup.Text = "Source";
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 4;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.tableLayoutPanel3.Controls.Add(this.otherSaveBtn, 3, 0);
            this.tableLayoutPanel3.Controls.Add(this.saveBtn, 2, 0);
            this.tableLayoutPanel3.Controls.Add(this.fileSelectionBtn, 1, 0);
            this.tableLayoutPanel3.Controls.Add(this.fileSelectionText, 0, 0);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(2, 17);
            this.tableLayoutPanel3.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 1;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(418, 36);
            this.tableLayoutPanel3.TabIndex = 7;
            // 
            // otherSaveBtn
            // 
            this.otherSaveBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.otherSaveBtn.Font = new System.Drawing.Font("SimSun", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.otherSaveBtn.Location = new System.Drawing.Point(330, 3);
            this.otherSaveBtn.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.otherSaveBtn.Name = "otherSaveBtn";
            this.otherSaveBtn.Size = new System.Drawing.Size(86, 30);
            this.otherSaveBtn.TabIndex = 5;
            this.otherSaveBtn.Text = "Save as...";
            this.otherSaveBtn.UseVisualStyleBackColor = true;
            this.otherSaveBtn.Click += new System.EventHandler(this.otherSaveBtn_Click);
            // 
            // saveBtn
            // 
            this.saveBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.saveBtn.Enabled = false;
            this.saveBtn.Font = new System.Drawing.Font("SimSun", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.saveBtn.Location = new System.Drawing.Point(240, 3);
            this.saveBtn.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.saveBtn.Name = "saveBtn";
            this.saveBtn.Size = new System.Drawing.Size(86, 30);
            this.saveBtn.TabIndex = 4;
            this.saveBtn.Text = "Save";
            this.saveBtn.UseVisualStyleBackColor = true;
            this.saveBtn.Click += new System.EventHandler(this.saveBtn_Click);
            // 
            // codeText
            // 
            this.codeText.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.codeText.Font = new System.Drawing.Font("Consolas", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.codeText.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.codeText.Location = new System.Drawing.Point(2, 71);
            this.codeText.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.codeText.Multiline = true;
            this.codeText.Name = "codeText";
            this.codeText.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.codeText.Size = new System.Drawing.Size(428, 435);
            this.codeText.TabIndex = 4;
            // 
            // compilePromptText
            // 
            this.compilePromptText.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.compilePromptText.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.compilePromptText.Location = new System.Drawing.Point(2, 512);
            this.compilePromptText.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.compilePromptText.Multiline = true;
            this.compilePromptText.Name = "compilePromptText";
            this.compilePromptText.ReadOnly = true;
            this.compilePromptText.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.compilePromptText.Size = new System.Drawing.Size(428, 134);
            this.compilePromptText.TabIndex = 3;
            // 
            // HexStreamGroup
            // 
            this.HexStreamGroup.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.HexStreamGroup.Controls.Add(this.tableLayoutPanel4);
            this.HexStreamGroup.Font = new System.Drawing.Font("SimSun", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.HexStreamGroup.Location = new System.Drawing.Point(438, 3);
            this.HexStreamGroup.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.HexStreamGroup.Name = "HexStreamGroup";
            this.HexStreamGroup.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.HexStreamGroup.Size = new System.Drawing.Size(184, 649);
            this.HexStreamGroup.TabIndex = 5;
            this.HexStreamGroup.TabStop = false;
            this.HexStreamGroup.Text = "Instruction stream";
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.ColumnCount = 1;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.Controls.Add(this.binText, 0, 3);
            this.tableLayoutPanel4.Controls.Add(this.tableLayoutPanel5, 0, 0);
            this.tableLayoutPanel4.Controls.Add(this.tableLayoutPanel6, 0, 1);
            this.tableLayoutPanel4.Controls.Add(this.bootAddrGroup, 0, 2);
            this.tableLayoutPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel4.Location = new System.Drawing.Point(2, 17);
            this.tableLayoutPanel4.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 4;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 43F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 43F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 52F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(180, 629);
            this.tableLayoutPanel4.TabIndex = 0;
            // 
            // binText
            // 
            this.binText.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.binText.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.binText.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.binText.Location = new System.Drawing.Point(2, 141);
            this.binText.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.binText.Multiline = true;
            this.binText.Name = "binText";
            this.binText.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.binText.Size = new System.Drawing.Size(176, 485);
            this.binText.TabIndex = 5;
            // 
            // tableLayoutPanel5
            // 
            this.tableLayoutPanel5.ColumnCount = 2;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48.29546F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 51.70454F));
            this.tableLayoutPanel5.Controls.Add(this.saveVerilog, 1, 0);
            this.tableLayoutPanel5.Controls.Add(this.compileBtn, 0, 0);
            this.tableLayoutPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel5.Location = new System.Drawing.Point(2, 3);
            this.tableLayoutPanel5.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.RowCount = 1;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(176, 37);
            this.tableLayoutPanel5.TabIndex = 0;
            // 
            // saveVerilog
            // 
            this.saveVerilog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.saveVerilog.Font = new System.Drawing.Font("SimSun", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.saveVerilog.Location = new System.Drawing.Point(87, 3);
            this.saveVerilog.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.saveVerilog.Name = "saveVerilog";
            this.saveVerilog.Size = new System.Drawing.Size(87, 31);
            this.saveVerilog.TabIndex = 2;
            this.saveVerilog.Text = "Verilog";
            this.saveVerilog.UseVisualStyleBackColor = true;
            this.saveVerilog.Click += new System.EventHandler(this.saveVerilog_Click);
            // 
            // compileBtn
            // 
            this.compileBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.compileBtn.Font = new System.Drawing.Font("SimSun", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.compileBtn.Location = new System.Drawing.Point(2, 3);
            this.compileBtn.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.compileBtn.Name = "compileBtn";
            this.compileBtn.Size = new System.Drawing.Size(81, 31);
            this.compileBtn.TabIndex = 0;
            this.compileBtn.Text = "Compilation";
            this.compileBtn.UseVisualStyleBackColor = true;
            this.compileBtn.Click += new System.EventHandler(this.compileBtn_Click);
            // 
            // tableLayoutPanel6
            // 
            this.tableLayoutPanel6.ColumnCount = 2;
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel6.Controls.Add(this.programBtn, 1, 0);
            this.tableLayoutPanel6.Controls.Add(this.portSelectionBox, 0, 0);
            this.tableLayoutPanel6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel6.Location = new System.Drawing.Point(2, 46);
            this.tableLayoutPanel6.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tableLayoutPanel6.Name = "tableLayoutPanel6";
            this.tableLayoutPanel6.RowCount = 1;
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel6.Size = new System.Drawing.Size(176, 37);
            this.tableLayoutPanel6.TabIndex = 1;
            this.tableLayoutPanel6.Paint += new System.Windows.Forms.PaintEventHandler(this.tableLayoutPanel6_Paint);
            // 
            // programBtn
            // 
            this.programBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.programBtn.Font = new System.Drawing.Font("SimSun", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.programBtn.Location = new System.Drawing.Point(119, 3);
            this.programBtn.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.programBtn.Name = "programBtn";
            this.programBtn.Size = new System.Drawing.Size(55, 31);
            this.programBtn.TabIndex = 3;
            this.programBtn.Text = "Write";
            this.programBtn.UseVisualStyleBackColor = true;
            this.programBtn.Click += new System.EventHandler(this.programBtn_Click);
            // 
            // portSelectionBox
            // 
            this.portSelectionBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.portSelectionBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.portSelectionBox.Font = new System.Drawing.Font("SimSun", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.portSelectionBox.FormattingEnabled = true;
            this.portSelectionBox.Location = new System.Drawing.Point(2, 3);
            this.portSelectionBox.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.portSelectionBox.Name = "portSelectionBox";
            this.portSelectionBox.Size = new System.Drawing.Size(113, 24);
            this.portSelectionBox.TabIndex = 0;
            this.portSelectionBox.DropDown += new System.EventHandler(this.InitializeCurrentPort);
            // 
            // bootAddrGroup
            // 
            this.bootAddrGroup.Controls.Add(this.bootAddrTextBox);
            this.bootAddrGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bootAddrGroup.Location = new System.Drawing.Point(2, 89);
            this.bootAddrGroup.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bootAddrGroup.Name = "bootAddrGroup";
            this.bootAddrGroup.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.bootAddrGroup.Size = new System.Drawing.Size(176, 46);
            this.bootAddrGroup.TabIndex = 6;
            this.bootAddrGroup.TabStop = false;
            this.bootAddrGroup.Text = "BOOT address";
            // 
            // bootAddrTextBox
            // 
            this.bootAddrTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bootAddrTextBox.Font = new System.Drawing.Font("SimSun", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.bootAddrTextBox.Location = new System.Drawing.Point(2, 17);
            this.bootAddrTextBox.Margin = new System.Windows.Forms.Padding(4);
            this.bootAddrTextBox.Name = "bootAddrTextBox";
            this.bootAddrTextBox.Size = new System.Drawing.Size(172, 24);
            this.bootAddrTextBox.TabIndex = 1;
            this.bootAddrTextBox.Text = "00008000";
            this.bootAddrTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // MainLayout
            // 
            this.MainLayout.ColumnCount = 4;
            this.MainLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 188F));
            this.MainLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 188F));
            this.MainLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 285F));
            this.MainLayout.Controls.Add(this.HexStreamGroup, 1, 0);
            this.MainLayout.Controls.Add(this.tableLayoutPanel2, 0, 0);
            this.MainLayout.Controls.Add(this.groupBox1, 2, 0);
            this.MainLayout.Controls.Add(this.MemoryDumpGroup, 3, 0);
            this.MainLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainLayout.Location = new System.Drawing.Point(0, 0);
            this.MainLayout.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.MainLayout.Name = "MainLayout";
            this.MainLayout.RowCount = 1;
            this.MainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 17F));
            this.MainLayout.Size = new System.Drawing.Size(1097, 655);
            this.MainLayout.TabIndex = 6;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 1;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.Controls.Add(this.compileGroup, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.codeText, 0, 1);
            this.tableLayoutPanel2.Controls.Add(this.compilePromptText, 0, 2);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(2, 3);
            this.tableLayoutPanel2.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 3;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 68F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 76F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 24F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(432, 649);
            this.tableLayoutPanel2.TabIndex = 6;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.tableLayoutPanel7);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox1.Location = new System.Drawing.Point(626, 3);
            this.groupBox1.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.groupBox1.Size = new System.Drawing.Size(184, 649);
            this.groupBox1.TabIndex = 7;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Serial view";
            // 
            // tableLayoutPanel7
            // 
            this.tableLayoutPanel7.ColumnCount = 1;
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel7.Controls.Add(this.userPortTextBox, 0, 1);
            this.tableLayoutPanel7.Controls.Add(this.tableLayoutPanel8, 0, 0);
            this.tableLayoutPanel7.Controls.Add(this.UserPortRecvCountLabel, 0, 2);
            this.tableLayoutPanel7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel7.Location = new System.Drawing.Point(2, 16);
            this.tableLayoutPanel7.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tableLayoutPanel7.Name = "tableLayoutPanel7";
            this.tableLayoutPanel7.RowCount = 3;
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 78F));
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel7.Size = new System.Drawing.Size(180, 630);
            this.tableLayoutPanel7.TabIndex = 0;
            // 
            // userPortTextBox
            // 
            this.userPortTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.userPortTextBox.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.userPortTextBox.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.userPortTextBox.Location = new System.Drawing.Point(2, 81);
            this.userPortTextBox.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.userPortTextBox.Multiline = true;
            this.userPortTextBox.Name = "userPortTextBox";
            this.userPortTextBox.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.userPortTextBox.Size = new System.Drawing.Size(176, 511);
            this.userPortTextBox.TabIndex = 6;
            // 
            // tableLayoutPanel8
            // 
            this.tableLayoutPanel8.ColumnCount = 2;
            this.tableLayoutPanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel8.Controls.Add(this.userPortClearBtn, 1, 1);
            this.tableLayoutPanel8.Controls.Add(this.userPortOpenCloseBtn, 1, 0);
            this.tableLayoutPanel8.Controls.Add(this.userPortShowHex, 0, 1);
            this.tableLayoutPanel8.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel8.Location = new System.Drawing.Point(2, 3);
            this.tableLayoutPanel8.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.tableLayoutPanel8.Name = "tableLayoutPanel8";
            this.tableLayoutPanel8.RowCount = 2;
            this.tableLayoutPanel8.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel8.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel8.Size = new System.Drawing.Size(176, 72);
            this.tableLayoutPanel8.TabIndex = 2;
            // 
            // userPortClearBtn
            // 
            this.userPortClearBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.userPortClearBtn.Font = new System.Drawing.Font("SimSun", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.userPortClearBtn.Location = new System.Drawing.Point(119, 39);
            this.userPortClearBtn.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.userPortClearBtn.Name = "userPortClearBtn";
            this.userPortClearBtn.Size = new System.Drawing.Size(55, 30);
            this.userPortClearBtn.TabIndex = 4;
            this.userPortClearBtn.Text = "Clear";
            this.userPortClearBtn.UseVisualStyleBackColor = true;
            this.userPortClearBtn.Click += new System.EventHandler(this.userPortClearBtn_Click);
            // 
            // userPortOpenCloseBtn
            // 
            this.userPortOpenCloseBtn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.userPortOpenCloseBtn.Font = new System.Drawing.Font("SimSun", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.userPortOpenCloseBtn.Location = new System.Drawing.Point(119, 3);
            this.userPortOpenCloseBtn.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.userPortOpenCloseBtn.Name = "userPortOpenCloseBtn";
            this.userPortOpenCloseBtn.Size = new System.Drawing.Size(55, 30);
            this.userPortOpenCloseBtn.TabIndex = 3;
            this.userPortOpenCloseBtn.Text = "Open";
            this.userPortOpenCloseBtn.UseVisualStyleBackColor = true;
            this.userPortOpenCloseBtn.Click += new System.EventHandler(this.userPortOpenCloseBtn_Click);
            // 
            // userPortShowHex
            // 
            this.userPortShowHex.AutoSize = true;
            this.userPortShowHex.Dock = System.Windows.Forms.DockStyle.Fill;
            this.userPortShowHex.Location = new System.Drawing.Point(2, 39);
            this.userPortShowHex.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.userPortShowHex.Name = "userPortShowHex";
            this.userPortShowHex.Size = new System.Drawing.Size(113, 30);
            this.userPortShowHex.TabIndex = 5;
            this.userPortShowHex.Text = "Hexadecimal display";
            this.userPortShowHex.UseVisualStyleBackColor = true;
            // 
            // UserPortRecvCountLabel
            // 
            this.UserPortRecvCountLabel.AutoSize = true;
            this.UserPortRecvCountLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UserPortRecvCountLabel.Location = new System.Drawing.Point(2, 598);
            this.UserPortRecvCountLabel.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.UserPortRecvCountLabel.Name = "UserPortRecvCountLabel";
            this.UserPortRecvCountLabel.Size = new System.Drawing.Size(176, 29);
            this.UserPortRecvCountLabel.TabIndex = 7;
            this.UserPortRecvCountLabel.Text = "Received: 0 B";
            // 
            // MemoryDumpGroup
            // 
            this.MemoryDumpGroup.Controls.Add(this.MemoryDumpLayout);
            this.MemoryDumpGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MemoryDumpGroup.Location = new System.Drawing.Point(814, 3);
            this.MemoryDumpGroup.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.MemoryDumpGroup.Name = "MemoryDumpGroup";
            this.MemoryDumpGroup.Padding = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.MemoryDumpGroup.Size = new System.Drawing.Size(281, 649);
            this.MemoryDumpGroup.TabIndex = 8;
            this.MemoryDumpGroup.TabStop = false;
            this.MemoryDumpGroup.Text = "Memory DUMP";
            // 
            // MemoryDumpLayout
            // 
            this.MemoryDumpLayout.ColumnCount = 1;
            this.MemoryDumpLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MemoryDumpLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 15F));
            this.MemoryDumpLayout.Controls.Add(this.MemContents, 0, 2);
            this.MemoryDumpLayout.Controls.Add(this.AdrLenSpecLayout, 0, 0);
            this.MemoryDumpLayout.Controls.Add(this.DUMPMemory, 0, 1);
            this.MemoryDumpLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MemoryDumpLayout.Location = new System.Drawing.Point(2, 16);
            this.MemoryDumpLayout.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.MemoryDumpLayout.Name = "MemoryDumpLayout";
            this.MemoryDumpLayout.RowCount = 3;
            this.MemoryDumpLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 74F));
            this.MemoryDumpLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.MemoryDumpLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MemoryDumpLayout.Size = new System.Drawing.Size(277, 630);
            this.MemoryDumpLayout.TabIndex = 1;
            // 
            // MemContents
            // 
            this.MemContents.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.MemContents.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MemContents.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.MemContents.Location = new System.Drawing.Point(2, 112);
            this.MemContents.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.MemContents.Multiline = true;
            this.MemContents.Name = "MemContents";
            this.MemContents.ReadOnly = true;
            this.MemContents.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.MemContents.Size = new System.Drawing.Size(273, 515);
            this.MemContents.TabIndex = 6;
            // 
            // AdrLenSpecLayout
            // 
            this.AdrLenSpecLayout.ColumnCount = 2;
            this.AdrLenSpecLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.AdrLenSpecLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.AdrLenSpecLayout.Controls.Add(this.StartAddr, 1, 0);
            this.AdrLenSpecLayout.Controls.Add(this.Length, 1, 1);
            this.AdrLenSpecLayout.Controls.Add(this.LengthTitle, 0, 1);
            this.AdrLenSpecLayout.Controls.Add(this.StartAddrTitle, 0, 0);
            this.AdrLenSpecLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.AdrLenSpecLayout.Location = new System.Drawing.Point(2, 3);
            this.AdrLenSpecLayout.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.AdrLenSpecLayout.Name = "AdrLenSpecLayout";
            this.AdrLenSpecLayout.RowCount = 2;
            this.AdrLenSpecLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.AdrLenSpecLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.AdrLenSpecLayout.Size = new System.Drawing.Size(273, 68);
            this.AdrLenSpecLayout.TabIndex = 0;
            // 
            // StartAddr
            // 
            this.StartAddr.Dock = System.Windows.Forms.DockStyle.Fill;
            this.StartAddr.Font = new System.Drawing.Font("SimSun", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.StartAddr.Location = new System.Drawing.Point(140, 4);
            this.StartAddr.Margin = new System.Windows.Forms.Padding(4);
            this.StartAddr.Name = "StartAddr";
            this.StartAddr.Size = new System.Drawing.Size(129, 24);
            this.StartAddr.TabIndex = 4;
            this.StartAddr.Text = "00010000";
            this.StartAddr.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // Length
            // 
            this.Length.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Length.Font = new System.Drawing.Font("SimSun", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.Length.Location = new System.Drawing.Point(140, 38);
            this.Length.Margin = new System.Windows.Forms.Padding(4);
            this.Length.Name = "Length";
            this.Length.Size = new System.Drawing.Size(129, 24);
            this.Length.TabIndex = 3;
            this.Length.Text = "80";
            this.Length.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // LengthTitle
            // 
            this.LengthTitle.AutoSize = true;
            this.LengthTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.LengthTitle.Location = new System.Drawing.Point(2, 34);
            this.LengthTitle.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.LengthTitle.Name = "LengthTitle";
            this.LengthTitle.Size = new System.Drawing.Size(132, 34);
            this.LengthTitle.TabIndex = 2;
            this.LengthTitle.Text = "Length (16 HEX):";
            this.LengthTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // StartAddrTitle
            // 
            this.StartAddrTitle.AutoSize = true;
            this.StartAddrTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.StartAddrTitle.Location = new System.Drawing.Point(2, 0);
            this.StartAddrTitle.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.StartAddrTitle.Name = "StartAddrTitle";
            this.StartAddrTitle.Size = new System.Drawing.Size(132, 34);
            this.StartAddrTitle.TabIndex = 0;
            this.StartAddrTitle.Text = "Start Address (16 HEX)";
            this.StartAddrTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // DUMPMemory
            // 
            this.DUMPMemory.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DUMPMemory.Location = new System.Drawing.Point(2, 77);
            this.DUMPMemory.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.DUMPMemory.Name = "DUMPMemory";
            this.DUMPMemory.Size = new System.Drawing.Size(273, 29);
            this.DUMPMemory.TabIndex = 1;
            this.DUMPMemory.Text = "DUMP memory";
            this.DUMPMemory.UseVisualStyleBackColor = true;
            this.DUMPMemory.Click += new System.EventHandler(this.DUMPMemory_Click);
            // 
            // serialPort
            // 
            this.serialPort.BaudRate = 115200;
            this.serialPort.ReadTimeout = 50;
            this.serialPort.WriteTimeout = 300;
            this.serialPort.DataReceived += new System.IO.Ports.SerialDataReceivedEventHandler(this.serialPort_DataReceived);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1097, 655);
            this.Controls.Add(this.MainLayout);
            this.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.Name = "MainForm";
            this.Text = "USTCRVSoC Tools";
            this.compileGroup.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel3.PerformLayout();
            this.HexStreamGroup.ResumeLayout(false);
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel4.PerformLayout();
            this.tableLayoutPanel5.ResumeLayout(false);
            this.tableLayoutPanel6.ResumeLayout(false);
            this.bootAddrGroup.ResumeLayout(false);
            this.bootAddrGroup.PerformLayout();
            this.MainLayout.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.tableLayoutPanel7.ResumeLayout(false);
            this.tableLayoutPanel7.PerformLayout();
            this.tableLayoutPanel8.ResumeLayout(false);
            this.tableLayoutPanel8.PerformLayout();
            this.MemoryDumpGroup.ResumeLayout(false);
            this.MemoryDumpLayout.ResumeLayout(false);
            this.MemoryDumpLayout.PerformLayout();
            this.AdrLenSpecLayout.ResumeLayout(false);
            this.AdrLenSpecLayout.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TextBox fileSelectionText;
        private System.Windows.Forms.Button fileSelectionBtn;
        private System.Windows.Forms.GroupBox compileGroup;
        private System.Windows.Forms.TextBox compilePromptText;
        private System.Windows.Forms.TextBox codeText;
        private System.Windows.Forms.Button saveBtn;
        private System.Windows.Forms.GroupBox HexStreamGroup;
        private System.Windows.Forms.TableLayoutPanel MainLayout;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.Button otherSaveBtn;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        private System.Windows.Forms.Button saveVerilog;
        private System.Windows.Forms.Button compileBtn;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel6;
        private System.Windows.Forms.Button programBtn;
        private System.Windows.Forms.ComboBox portSelectionBox;
        private System.Windows.Forms.TextBox binText;
        private System.IO.Ports.SerialPort serialPort;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox bootAddrGroup;
        private System.Windows.Forms.TextBox bootAddrTextBox;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel7;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel8;
        private System.Windows.Forms.Button userPortOpenCloseBtn;
        private System.Windows.Forms.TextBox userPortTextBox;
        private System.Windows.Forms.Button userPortClearBtn;
        private System.Windows.Forms.CheckBox userPortShowHex;
        private System.Windows.Forms.Label UserPortRecvCountLabel;
        private System.Windows.Forms.GroupBox MemoryDumpGroup;
        private System.Windows.Forms.TableLayoutPanel MemoryDumpLayout;
        private System.Windows.Forms.TextBox MemContents;
        private System.Windows.Forms.TableLayoutPanel AdrLenSpecLayout;
        private System.Windows.Forms.TextBox StartAddr;
        private System.Windows.Forms.TextBox Length;
        private System.Windows.Forms.Label LengthTitle;
        private System.Windows.Forms.Label StartAddrTitle;
        private System.Windows.Forms.Button DUMPMemory;

    }
}

